apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
# Valor em base64. Gere o seu com: echo -n "seu_token" | base64
type: Opaque
data:
  GITHUB_TOKEN: "c2V1LXRva2VuLWFxdWk="
