title: Cloud Engineer Roadmap
description: Um guia de estudos gratuito e em português para quem está começando em Cloud Engineering (DevOps / SRE / Platform Engineering).
url: https://therenanlira.github.io
lang: pt_BR
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og-image.png
