apiVersion: v1
kind: Secret
metadata:
  name: backstage-auth-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_CLIENT_ID: "Seu Client ID aqui"
  GITHUB_CLIENT_SECRET: "Seu Client Secret aqui"
